@startuml
'https://plantuml.com/class-diagram
class App{
    + main()
    + start()
 }
 class ToDoList{
    - string listName
    - ArrayList[100] <items> allItems

    + addItem(Item)
    + deleteItem(Item)
    + editItem(Item)
    + displayItems()
    + displayComplete()
    + displayIncomplete()
    }
class ListAll{
    -ArrayList <toDoLists> allToLists

    +clearList(ToDoList)
    +saveList()
    +saveListAll()
    +loadList()
    +loadListAll()

}
class Item{
    -boolean complete
    -string itemDesc [256]
    -date dueDate

    +editDesc()
    +editDate()
    +isComplete(Boolean)
}
class Controller{
    +saveListClicked(ActionEvent)
    +loadListClicked(ActionEvent)
    +clearListClicked(ActionEvent)

    +addItemClicked(ActionEvent)
    +deleteItemClicked(ActionEvent)
    +editItemClicked(ActionEvent)
    +setCompleteItemClicked(ActionEvent)

    +displayItemsClicked(ActionEvent)
}

javafx.Application <|-- App
App -- Controller

Controller *--> ListAll
ListAll *--> ToDoList
ToDoList *--> Item
@enduml